# Generated by Django 3.2.6 on 2021-09-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_auto_20210729_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('sizes', 'size'), ('colors', 'color')], default='size', max_length=120)),
                ('image', models.ImageField(default=None, upload_to='products/variations/')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
